model:
  dimensionality_reduction: PCA
  reduced_dim: 128
  sbert_model: snunlp/KR-SBERT-V40K-klueNLI-augSTS
  xgboost_params:
    learning_rate: 0.1
    max_depth: 5
    n_estimators: 100
    objective: reg:squarederror
    random_state: 42
recommendation:
  similarity_weight: 0.6
  tag_weight: 0.4
